name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Test on NodeJS v12
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm i
      - run: npm test
        env:
          host: "db.ghbox.io"
          database: "mykv"
          user: "mykv"
          password: ${{ secrets.DB_PASSWORD }}
